DROP TABLE IF EXISTS DEMO_COMPANY;

######用户档案##
CREATE TABLE DEMO_COMPANY (
 COMPANY_ID BIGINT  NOT NULL AUTO_INCREMENT,
 COMPANY_NAME VARCHAR(50),
 COMPANY_PROPERTY VARCHAR(50),
 COMPANY_NUM INT,
 INCOME INT,
 LEGAL_REPRESENTATIVE VARCHAR(250),
 PRIMARY KEY (COMPANY_ID)
)DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

###导入数据###
INSERT INTO DEMO_COMPANY VALUES ( 1,'浪潮软件','国企', 4000, 90000000, '某某某');
INSERT INTO DEMO_COMPANY VALUES ( 2,'浪潮国际','国企', 3000, 70000000, '某某某');

